=== sdsouza42/PastProjects/Coding Sample/Web/xml/Jan12/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="ename" type="xs:string"/>
  <xs:element name="eage" type="xs:integer"/>
  <xs:element name="esal" type="xs:integer"/>
  
  
  <xs:complexType name="emptype">
    <xs:sequence>
      <xs:element ref="ename" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="eage" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="esal" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>  
  </xs:complexType>
  
  <xs:element name="emp" type="emptype"></xs:element>
  
  <xs:element name="employee">
    <xs:complexType>
      <xs:sequence>
          <xs:element ref="emp" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  
</xs:schema>

=== sdsouza42/PastProjects/Coding Sample/Web/xml/Jan12/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employee.xsd">
  <emp>
    <ename>Amit</ename>
    <eage>22</eage>
    <esal>10000</esal>
  </emp>
  <emp>
    <ename>Anil</ename>
    <eage>22</eage>
    <esal>10000</esal>
  </emp>
</employee>
